# your domain
domain: ybproxypool.herokuapp.com

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files: 
  # use local file
  #- ./config/source.yaml
  # use web file
  - https://raw.githubusercontent.com/wangyingbo/proxypool-1/master/config/source.yaml
